---
base_image: ubuntu:18.04
container_name: trabeet_build_container
image_namespace: dueyfinster
image_name: trabeet

ansible_python_interpreter: /usr/bin/python3

# Handy utilities.
pkgs_to_install:
  - curl
  - python3-pip
  - ruby-dev
