#+TITLE:     trabeet container (Built with Ansible)
#+AUTHOR:    Neil Grogan
[[https://cloud.docker.com/repository/registry-1.docker.io/dueyfinster/trabeet/builds][Docker image]] for downloading for Plex using Transmission & youtube-dl, all
controlled via webhooks.

This project is composed of two main parts:

  - *Ansible project*: This project is maintained on GitHub: [[https://github.com/dueyfinster/trabeet][dueyfinster/trabeet]]. Please file issues, support requests, etc. against this GitHub repository.
  - *Docker Hub Image*: If you just want to use [[https://hub.docker.com/r/dueyfinster/trabeet/][the `dueyfinster/trabeet` Docker image]] in your project, you can pull it from Docker Hub.

** Diagram
#+begin_src ditaa :file flow.svg :exports results
+--------------------+    +-------------+   +-------------+   +------------------+   +-------------------+   
|cGRE curl (magnet:) +--->|cYEL         |   |cYEL         |   |cGRE              |   |cGRE               |
+--------------------+    |    Nginx    +-->|   Webhook   +-->+     Download     +-->+  Process Metadata +--------------+
|c37F curl (https:)  +--->|    (8080)   |   |             |   |   Transmission   |   |  Beets (Music)    |              |
+--------------------+    +---+-----+---+   +-------------+   |                  |   |  Filebot (Video)  |              v
                              ^     |              |          +-------+----------+   +-------------------+      +-------+-------+
                              |     |              |                  ^                                         |cYEL {s}       |
                              |     |              |                  |                                         |  Plex Library |        
                       +---------+  \--------------|------------------/                                         |               |
                       |   Web   |                 V                                                            +-------+-------+
                       |  Browser|        +--------+-------+                 +------------------+                       ^
	               +---------+        |c37F            |                 |c37F              |                       |
                                          |    Download    |                 | Process Metadata |                       |
                                          |   youtube-dl   +---------------->+ Beets (Music)    +-----------------------/                    
                                          |                |                 | or None (Video)  |   
                                          +----------------+                 +------------------+
#+end_src

#+RESULTS:
[[file:flow.svg]]

** To use
Extend the docker image, add custom config/scripts and mount:

- Downloads directory at /downloads
- Plex Directory at /media (Assuming standard Plex library layout of 'Movies','TV Shows', 'Videos', 'Music')
- Send requests via curl ~curl -X POST --data "token=<MYTOKEN>" --data "uri=https://www.youtube.com/watch?v=<MYVIDEO>" --data "type=<Movies|TV Shows|Music|Video>" http://<my_ip>:8080/hooks/yt-dl~

See sample [[docker-compose-sample.yml][docker-compose]] file for reference.
