plugins: fetchart embedart convert scrub replaygain lastgenre chroma web
directory: /media/Music
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

match:
  strong_rec_thresh: 0.35

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title 

import:
  write: yes
  copy: no
  move: yes
  default_action: apply
  from_scratch: yes
  log: /var/log/beets.log

ignore: .AppleDouble ._* *~ .DS_Store
ignore_hidden: yes
plugins: [chroma, plexupdate, fetchart, embedart, scrub, lastgenre, convert]

chroma:
  auto: yes

#replaygain:
#  backend: gstreamer

embedart:
  auto: yes

fetchart:
  auto: yes

scrub:
  auto: yes

lastgenre:
  auto: yes
  source: album

plex:
  host: plex
  port: 32400

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

convert:
  auto: no
  ffmpeg: /usr/bin/ffmpeg
  opts: -ab 320k -ac 2 -ar 48000
  max_bitrate: 320
  threads: 1
