#!/bin/bash
# Refreshes the Plex libary
test -z $1 && echo "need library ID number to refresh! $0 <message>" && exit 1

# Refresh Music Library
curl "$PLEX_HOST"/library/sections/$1/refresh?X-Plex-Token="$PLEX_TOKEN"
