#!/bin/bash
if [ $# -eq 0 ]
  then
    echo "need message to send! $0 <message>" && exit 1
fi

curl -s \
  --form-string "token=$PUSHOVER_TOKEN" \
  --form-string "user=$PUSHOVER_USER" \
  --form-string "message=$@" \
  https://api.pushover.net/1/messages.json
